import { createFileRoute } from "@tanstack/react-router";
import { LegalPage, LegalSection } from "@/components/legal-page";
import { Button } from "@/components/ui/button";
import { openCookieSettings } from "@/components/cookie-consent";
import { useI18n } from "@/lib/i18n";

export const Route = createFileRoute("/cookies")({ head: () => ({ meta: [
  { title: "Cookie notice | Momentum One" }, { name: "description", content: "Momentum One cookie choices and storage information." }, { property: "og:title", content: "Cookie notice | Momentum One" }, { property: "og:description", content: "Momentum One cookie choices and storage information." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" },
] }), component: Cookies });
function Cookies() { const { locale, t } = useI18n(); const c: readonly [string, string, string, string, string, string, string, string, string] = locale === "ro" ? ["Cookies", "Notificare cookies", "Tu controlezi stocarea opțională. Stocarea esențială rămâne activă pentru securitate și funcțiile contului.", "Stocare esențială", "Folosim stocarea esențială pentru autentificare, securitate, progresul aplicației și alegerea privind cookies. Aceste funcții sunt necesare serviciilor solicitate.", "Analiză și marketing opționale", "Instrumentele opționale ne pot ajuta să măsurăm utilizarea site-ului sau campaniile. Acestea nu se încarcă înainte să le accepți.", "Schimbă alegerea", "Poți redeschide panoul cookies oricând. Respingerea cookie-urilor opționale nu te împiedică să aplici sau să te autentifici."] : locale === "es" ? ["Cookies", "Aviso de cookies", "Tú controlas el almacenamiento opcional. El almacenamiento esencial permanece activo para la seguridad y las funciones de la cuenta.", "Almacenamiento esencial", "Utilizamos almacenamiento esencial para el acceso, la seguridad, el progreso de la solicitud y tu elección de cookies. Estas funciones son necesarias para los servicios solicitados.", "Análisis y marketing opcionales", "Las herramientas opcionales pueden ayudarnos a medir el uso del sitio o las campañas. No se cargan hasta que las aceptas.", "Cambiar tu elección", "Puedes volver a abrir el panel de cookies en cualquier momento. Rechazar las cookies opcionales no impide solicitar plaza ni iniciar sesión."] : ["Cookies", "Cookie notice", "You control optional website storage. Essential storage remains available so security and account features can work.", "Essential storage", "We use essential browser storage for authentication, security, application progress, and your cookie choice. These features are necessary for services you request.", "Optional analytics and marketing", "Optional tools may help measure website use or campaigns. They must not load until you accept them. This site currently defaults to essential storage only unless you choose otherwise.", "Change your choice", "You can reopen the cookie panel at any time. Rejecting optional cookies does not prevent you from applying or signing in."]; return <LegalPage eyebrow={c[0]} title={c[1]} intro={c[2]}>
  <LegalSection title={c[3]}><p>{c[4]}</p></LegalSection>
  <LegalSection title={c[5]}><p>{c[6]}</p></LegalSection>
  <LegalSection title={c[7]}><p>{c[8]}</p><Button onClick={openCookieSettings} className="mt-3">{t("footer.settings", undefined, "Open cookie settings")}</Button></LegalSection>
  <LegalSection title="Review"><p>The final list of providers, cookie names, purposes, and lifetimes must be updated whenever an analytics, advertising, embedded media, or chat provider is added.</p></LegalSection>
</LegalPage>; }